set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports green]
set_property IOSTANDARD LVCMOS33 [get_ports red]
set_property IOSTANDARD LVCMOS33 [get_ports warn]
set_property IOSTANDARD LVCMOS33 [get_ports k1]
set_property IOSTANDARD LVCMOS33 [get_ports k2]
set_property IOSTANDARD LVCMOS33 [get_ports k3]
set_property IOSTANDARD LVCMOS33 [get_ports k4]
set_property IOSTANDARD LVCMOS33 [get_ports p1]
set_property IOSTANDARD LVCMOS33 [get_ports p2]
set_property IOSTANDARD LVCMOS33 [get_ports p3]
set_property IOSTANDARD LVCMOS33 [get_ports p4]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P5 [get_ports reset]
set_property PACKAGE_PIN F6 [get_ports green]
set_property PACKAGE_PIN K2 [get_ports red]
set_property PACKAGE_PIN H4 [get_ports warn]
set_property PACKAGE_PIN U3 [get_ports p1]
set_property PACKAGE_PIN U2 [get_ports p2]
set_property PACKAGE_PIN V2 [get_ports p3]
set_property PACKAGE_PIN V5 [get_ports p4]
set_property PACKAGE_PIN R2 [get_ports k1]
set_property PACKAGE_PIN M4 [get_ports k2]
set_property PACKAGE_PIN N4 [get_ports k3]
set_property PACKAGE_PIN R1 [get_ports k4]

